### PR TITLE
feature: added search functionality

### PR DESCRIPTION
**Pull request by Qloozen**
- Added search toggle with fancy ease animations.
- If you have typed something in the input you can't hide the searchbar (only if it's empty)

### CODE REVIEW

**Comment by deBasMan21** [comment]
Isnt it better to be able to close the searchbar but it automatically removes the search tag when you do?

**Comment by deBasMan21** [comment]
Is it easy to also add the filter for skilllevel?

**Comment by Qloozen** [comment]
> Isnt it better to be able to close the searchbar but it automatically removes the search tag when you do?

Yes that is better indeed, I will fix that

> Is it easy to also add the filter for skilllevel?

I think its pretty easy with a pipe

**Comment by Qloozen** [comment]
- Added filter (chip buttons) above the searchbars
- Clean any filter when search button is clicked away
- Fixed UI not responding with filter pipe (made pipe impure)

**Review by deBasMan21 — APPROVED** [review]

**Pull request merged**
